### ISSUE TITLE
Basic ipython setup

### ISSUE THREAD

**Issue by jkirchman** [aps-8id-trr/ipython-8idiuser#1]
Let's start with the basic ipython setup, adding the motors to be 
scanned and the area detectors and counters.

**Comment by prjemian** [comment]
CAUTION:  There's an existing ~/.ipython directory with non-trivial content.  Let's not overwrite it.  Can we blend in?

**Comment by prjemian** [comment]
Can specify al alternate for `~/.ipython/`.  See: https://ipython.readthedocs.io/en/stable/development/config.html#configuration-file-location

**Comment by prjemian** [comment]
We discovered that 8ID has a dual undulator since the `APS_devices.ApsUndulator()` could not connect.

```

aps = APS_devices.ApsMachineParametersDevice(name="aps")
sd.baseline.append(aps)

undulator = APS_devices.ApsUndulatorDual("ID08", name="undulator")
sd.baseline.append(undulator)
```

**Comment by prjemian** [comment]
Sample startup directory here: https://github.com/BCDA-APS/use_bluesky/tree/master/ipython_setup/startup

**Comment by prjemian** [comment]
We'll do the setup in a new ipython directory: `~/.ipython-bluesky/` to avoid the existing `~/.ipython/` directory.  We can merge those later if the beam line says OK.

**Comment by prjemian** [comment]
The usual [setup](https://github.com/BCDA-APS/use_bluesky/blob/465a9eea81f9502e3a73d7745a196649215c9436/ipython_setup/install_bluesky_profile_for_ipython.sh#L31) writes into the user's directory.  `ipython profile create {PROFILE1}`

we will try this:

    ipython --ipython-dir=~/.ipython-bluesky/ profile create bluesky

**Comment by prjemian** [comment]
Now, clone this repository into that directory:

    cd ~/.ipython-bluesky/
    git clone https://github.com/aps-8id-trr/ipython-8idiuser ./

**Comment by prjemian** [comment]
Let's get the startup directory template:

```
cd /tmp
git clone https://github.com/BCDA-APS/use_bluesky
cd use_bluesky/ipython_setup/startup
tar cf - * | (cd ~/.ipython-bluesky/profile_bluesky/startup && tar xvf -)
```

**Comment by prjemian** [comment]
Edit in `21-signals.py` and uncomment the `aps` and `undulator` devices and change the `ID45` to the correct beam line.

**Comment by prjemian** [comment]
Let's try to start that profile now:

    ipython  --ipython-dir=~/.ipython-bluesky/ --profile=bluesky

**Comment by prjemian** [comment]
This failed to start due to mongodb configuration troubles.  Fix them tomorrow.  Once we fix the mongodb server host name in the YAML file, we'll symbolic link that YAML file into the directory where databroker expects to find it.  (For some reason, databroker does not expect to find it in the ipython profile's startup directory.)

```
mkdir -p ${HOME}/.config/databroker
cd ${HOME}/.config/databroker
ln -s ../../.ipython-bluesky/profile_bluesky/startup/mongodb_config.yml ./
```

**Comment by prjemian** [comment]
With #3 complete, we come back to finish here.

**Comment by prjemian** [comment]
mongodb server is `s8idapps`

**Comment by prjemian** [comment]
Now we have a clean startup.  Need to use simulation to test bluesky scans.  Here's a first "scan".

```
import ophyd.sim
sim = ophyd.sim.hw()
RE(bp.count([sim.det]))
```
