### ISSUE TITLE
When can we test for a full day?

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#106]

**Comment by qzhang234** [comment]
@prjemian I propose 11/23, the beginning of the Rigaku detector beamtime. @sureshnaps @ericmdufresne What do you think?

Also the Rigaku people will be at APS starting from 22 nd to implement the EPICS interface for Rigaku. I believe the BlueSky part will have to be changed accordingly as well. @prjemian Would you like to meet the Rigaku team on 22nd?

**Comment by prjemian** [comment]
OK, to both

**Comment by prjemian** [comment]
On that Friday (11/22), I have a commitment from 2-4 regarding upgrade of the USAXS instrument.

**Comment by prjemian** [comment]
I updated the [milestone](https://github.com/aps-8id-trr/ipython-8idiuser/milestone/8 to show beam time on Saturday, 11/23.
