### ISSUE TITLE
detector-specific configuration for XPCS

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#107]
In #45, the remaining [TODO items](https://github.com/aps-8id-trr/ipython-8idiuser/issues/45#issuecomment-551878615) are related and describe a base class : subclass structure where the subclasses are specific for each detector.  That's an example of when direct translation from SPEC (a procedural language) is better replaced by an object structure.  We have existing examples like this translation from procedures to objects in the `AD_Acquire()` code, when we ask the detector to configure itself for staging and for metadata setup.

https://github.com/aps-8id-trr/ipython-8idiuser/blob/007747e3076b001d324a26d455318b727be6358e/profile_bluesky/startup/50-controls.py#L511-L513

https://github.com/aps-8id-trr/ipython-8idiuser/blob/007747e3076b001d324a26d455318b727be6358e/profile_bluesky/startup/50-controls.py#L553-L555

**Comment by prjemian** [comment]
Perhaps we define a method that appears in any detector needing this support (now: Lambda and Rigaku).  

```
    def xpcs_loop(self, *args, **kwargs):
        pass    # TODO:
```

Such as just before: https://github.com/aps-8id-trr/ipython-8idiuser/blob/c5d8e91b5b5d27d0934cc801930c333f71225a36/profile_bluesky/startup/26-lambda.py#L99 and https://github.com/aps-8id-trr/ipython-8idiuser/blob/7b4ebc36dac0d3384eb23bf61e171235d7bbfd8a/profile_bluesky/startup/25-areadetector-rigaku.py#L98

**Comment by prjemian** [comment]
@sureshnaps What should these routines do?  Where are the SPEC macros?

**Comment by sureshnaps** [comment]
Pete,
I have compiled a set of macros which I believe will make it complete for lambda for all operating modes. These are kind of messy. I would think that many of this would be similar for Rigaku when those features are made available in the API/epics. We can go over these together on Monday as that will make it easier.

The pvs related to SG and there is also a user transform related to SG that can all go into the SG module.

Will this work? Sorry for the piecemeal code.

Suresh

**Comment by sureshnaps** [comment]
@prjemian /home/beams/8IDIUSER/Stuff_needed_for_Bluesky/lambda_macros.mac
I could not figure out how to load the text file, cut paste I could have done.

**Comment by prjemian** [comment]
@sureshnaps This is great.  I'll find it with that.

**Comment by prjemian** [comment]
The soft glue macros belong to the soft glue device support.  The lambda macros belong to the Lambda's cam device support.

**Comment by prjemian** [comment]
@sureshnaps : Where is this SPEC macro defined? `ccdset_DataType_ad`

**Comment by prjemian** [comment]
@sureshnaps : ... `ccdget_DataType_ad`

**Comment by sureshnaps** [comment]
CCDPV is "8LAMDA1:cam1:"
def ccdget_DataType_Lambda 'epics_get(sprintf("%sDataType_RBV",CCDPV),"short")'

def ccdset_DataType_Lambda '{
    if ($# != 1) {
        eprint "Usage: ccdset_DataType_Lambda $1"
        eprint "$1=3 for UInt16"
        exit
    }
    epics_put((sprintf("%sDataType",CCDPV)), $1)
    sleep(0.1)
}'

**Comment by prjemian** [comment]
## checklist

| SPEC macro | Bluesky | startup file |
| --- | --- | --- |
| `Start_SoftGlue_Trigger` | `soft_glue.start_trigger()` | `10-devices.py` |
| `Reset_SoftGlue_Trigger` | `soft_glue.reset_trigger()` | `10-devices.py` |
| `external_trigger_mode_setup_Lambda` | `lambdadet.cam.setup_trigger_mode_external()` | `26-lambda.py` |
| `internal_trigger_mode_setup_Lambda` | `lambdadet.cam.setup_trigger_mode_internal()` | `26-lambda.py` |
| `external_trigger_logic_setup_Data_Lambda` | `lambdadet.cam.setup_trigger_logic_external()` | `26-lambda.py` |
| `ccdget_Lambda_BadFrameCount` | `lambdadet.cam.getBadFrameCount` | `26-lambda.py` |
| `ccdset_time_Lambda` | `lambdadet.cam.setTime()` | `26-lambda.py` |
| `Lambda_modes_setup` | `lambdadet.cam.setup_modes()` | `26-lambda.py` |
| `ccdset_TriggerMode_Lambda` | `lambdadet.cam.setTriggerMode()` | `26-lambda.py` |
| `ccdset_OperatingMode_Lambda` | `lambdadet.cam.setOperatingMode()`  | `26-lambda.py` |
| `ccdset_compr_params_ad_Lambda` | `` | `` |
| `ccdset_RawMode_params_ad_Lambda` | `` | `` |
| `ccd_getcounts_ad_Lambda` | `` | `` |
| `ccdget_DataType_ad` | `lambdadet.cam.getDataType`  | `26-lambda.py` |
| `ccdset_DataType_ad` | `lambdadet.cam.setDataType()`  | `26-lambda.py` |
| `ccdset_ImageMode` | `lambdadet.cam.setImageMode()`  | `26-lambda.py` |

**Comment by prjemian** [comment]
@sureshnaps : Ah, yes, the `8LAMDA1:cam1:DataType` PV.  The rest is clear.  (sounds of palm to forehead heard in background)

**Comment by sureshnaps** [comment]
@prjemian Every time I think I can add these pvs and then I see your professional code, then I decide it is better you do it, good (for us) and bad (for you).

**Comment by prjemian** [comment]
**problem**:  This PV (`8LAMBDA1:IMMout:FullFileName`) is not responding the way I expected.  Thought we have read this before but now it is not responding.

```
    # FIXME: TimeoutError: 8LAMBDA1:IMMout:FullFileName could not connect within 1.0-second timeout.
    full_file_name = Component(EpicsSignalRO, "FullFileName", string=True, kind='config')
```

**Comment by prjemian** [comment]
Maybe I have the PV name wrong.

**Comment by sureshnaps** [comment]
There is only a RBV for this PV for some reason:
8LAMBDA1:IMMout:FullFileName_RBV
