### ISSUE TITLE
TimeoutError: 8LAMBDA1:IMMout:FullFileName 

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#108]
We want the full file name for use with the `ADAcquire()` plan, as it is returned in the detector's `plugin_file_name` method.  Is this PV name incorrect?  While testing https://github.com/aps-8id-trr/ipython-8idiuser/issues/107#issuecomment-552615162, we received this `TimeoutError`.

**Comment by prjemian** [comment]
Check the GUI screens and confirm the PV name is correct.

**Comment by prjemian** [comment]
@sureshnaps [confirms](https://github.com/aps-8id-trr/ipython-8idiuser/issues/107#issuecomment-552620912) there is only a RBV for this PV:

```
snow% caget 8LAMBDA1:IMM0:FullFileName_RBV
8LAMBDA1:IMM0:FullFileName_RBV 256 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
snow% caget -S 8LAMBDA1:IMM0:FullFileName_RBV
8LAMBDA1:IMM0:FullFileName_RBV 
```

**Comment by sureshnaps** [comment]
@prjemian In 26-lambda.py, line 120 should be the same like line 106 with the max. I looked through the code, reads very elegant.

**Comment by sureshnaps** [comment]
@prjemian  good point. This tells us that we need another condition. This EXT_TRIGGER=1 mode is not widely used so far, in fact hardly used but is starting to get used lately.

elif self.EXT_TRIGGER == 1 and self.getOperatingMode == 1:
            # important thing to be aware:
            # lambda does not support acquire_period in any way, 
            # except with trigger per frame mode
            yield from bps.mv(pvDELAY_B, exposure_time)  # AcquireTime in area detector
            # yield from bps.sleep(0.05)
            yield from bps.mv(pvDELAY_A, exposure_time + 0.0011)  # AcquirePeriod in area detector
            # yield from bps.sleep(0.05)

elif self.EXT_TRIGGER == 1 and self.getOperatingMode == 0:
            # important thing to be aware:
            # lambda does not support acquire_period in any way, 
            # except with trigger per frame mode
            yield from bps.mv(pvDELAY_B, exposure_time)  # AcquireTime in area detector
            # yield from bps.sleep(0.05)
            yield from bps.mv(pvDELAY_A, exposure_time)  # AcquirePeriod in area detector
            # yield from bps.sleep(0.05)
