### ISSUE TITLE
setup lambda detector

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#11]
Lambda 750K: "8LAMBDA1:"

See https://github.com/aps-8id-trr/ipython-8idiuser/issues/9#issuecomment-515158094 for a screenshot of the `cam1` interface.

**Comment by prjemian** [comment]
Looking in [ophyd](https://github.com/bluesky/ophyd/blob/master/ophyd/areadetector/cam.py), there is no instance of the Lambda  detector.  We'll need to make one.  It will be similar to any of them in that file, such as the [Andor](https://github.com/bluesky/ophyd/blob/master/ophyd/areadetector/cam.py#L206-L217), we need to define any attributes that are not already defined in [CamBase](https://github.com/bluesky/ophyd/blob/master/ophyd/areadetector/cam.py#L206-L217).  Note, we *could* use [`AreaDetectorCam`](https://github.com/bluesky/ophyd/blob/d3cd9b942d1fe1fd7a77355f95e5b7cfe8bb6289/ophyd/areadetector/cam.py#L131-L132) as our base class but that is identical.  Why bother?

**Comment by prjemian** [comment]
Here's an example from [2-BM-B (tomo)](https://github.com/APS-2BM-MIC/ipython-user2bmb/blob/94301cff74be34b67e4642d264bc83739f22d532/profile_2bmb/startup/25-PG3-grasshopper.py#L38-L52).  It's actually pretty easy.  The hardest part is identifying the parts to add.

**Comment by sureshnaps** [comment]
I think eiger from nsls2 CHX might be closer to Lambda. The point grey might have too many other features that a counting detector might not. Or we can always modify to suit lambda.

**Comment by prjemian** [comment]
Right.  Shows the process of what we will do. But make it specific to the
Lambda

**Comment by prjemian** [comment]
Basic configuration of Lambda 750K is setup on a branch.  By default, the HDF5 plugin is configured so that Bluesky sets the file names.  These are UUID names that are tracked through the `databroker` which means it is possible to get the image by using the databroker tools.

An alternative setup can be used where the HDF5 file names are configured through the area detector (as you normally have done).  The changeover is easy.  On this line: https://github.com/aps-8id-trr/ipython-8idiuser/blob/16ffdf63a1c81d8f225e16fee97e1dc659aad567/profile_bluesky/startup/25-areadetector.py#L51 replace `Plugin_HDF5_Bluesky_Names` with `Plugin_HDF5_EPICS_Names`

**Comment by prjemian** [comment]
@sureshnaps : about making this specific to the Lambda 750K, this is a start: https://github.com/aps-8id-trr/ipython-8idiuser/blob/16ffdf63a1c81d8f225e16fee97e1dc659aad567/profile_bluesky/startup/25-areadetector.py#L12-L18

**Comment by prjemian** [comment]
beam line uses the IMM plugin with area detector (see #24)

**Comment by prjemian** [comment]
might not be using the HDF5 plugin, be prepared

**Comment by prjemian** [comment]
OK to merge the branch without closing this issue.

**Comment by prjemian** [comment]
The detector has been tested with `bp.count`.  Will open new issues as identified.
