### ISSUE TITLE
support the Aerotech fly stage

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#111]
```
quartz% git grep -i fly
15-spec-config.py:#flyz = EpicsMotor('8idiAERO:aero:c0:m1', name='flyz', labels=("motor",))
```

```
    if (FLY_SCAN_YES_NO) {
        flyscan_setup FLY_START_POS FLY_END_POS FLY_SPEED   ##start,end,speed in mm/sec
        flyscan_taxi
        flyscan_start
    }
```

**Comment by prjemian** [comment]
This is also known as the *translation* stage that users may choose to use in their own custom macros.

**Comment by prjemian** [comment]
The *taxi*/*fly* mode is well-known from other beam lines.  Should not be difficult to support.

**Comment by qzhang234** [comment]
@prjemian I was going to open this but then saw that you did it already, so I would just like to comment that with this we'll be able to start building the generic Rigaku macro and commence general user operation in BS.

**Comment by prjemian** [comment]
But that was the easiest step.  Next, need to find the SPEC code.  That comes from looking through the macros directories.

Then, create a Device to support: `setup()`, `taxi()`, and `fly()` methods.  We'll look at 2-BM-B tomo for an ophyd example.

**Comment by prjemian** [comment]
SPEC macros (all from `~/local_macros/Aerotech_flyscan.mac`)

<details>
<summary>Aerotech_flyscan.mac</summary>
<p>

```
def flyscan_setup '{

if ($# != 3) {
	eprint "Usage: flyscan_setup start_pos end_pos slew_speed"
	exit
}

epics_put("8idiAERO:PSOFly1:startPos",$1)
epics_put("8idiAERO:PSOFly1:endPos",$2)
epics_put("8idiAERO:PSOFly1:slewSpeed",$3)

printf("Fly scan set up is done\n");
}'


def flyscan_taxi '{

epics_put("8idiAERO:PSOFly1:taxi",1);


printf("Waiting for Fly scan TAXI position to be reached...\n");
while (epics_get("8idiAERO:PSOFly1:taxi") != "Done") {
	sleep(0.01);
}

}'


def flyscan_start '{

epics_put("8idiAERO:PSOFly1:fly",1);


printf("Waiting for Fly scan to start...\n");
while (epics_get("8idiAERO:PSOFly1:fly") != "Fly") {
	sleep(0.01);
}

}'
```

Also, since this an Aerotech doing the fly scan, use 9-ID-C USAXS as the template.
</p>
</details>

**Comment by prjemian** [comment]
Right the first time, that code is in 2-BM-B tomo repo:  https://github.com/APS-2BM-MIC/ipython-user2bmb/blob/062b6b4b34dbe9b7d57256d8d6b2c5852aaca048/profile_bluesky/startup/10-devices.py#L43-L137
