### ISSUE TITLE
metadata helper fails with certain filename strings

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#113]
As noted in https://github.com/aps-8id-trr/ipython-8idiuser/issues/87#issuecomment-557815983:

> The python code fails when there are special characters in the file name including space. This is not intended but done occasionally done by mistake by the users. When this happens, helper daemon quits. Is there a way to catch the exception and preventing the exiting?

**Comment by prjemian** [comment]
Yes.  I'll add a call to a function that will translate a given text into an acceptable file name.

**Comment by prjemian** [comment]
@sureshnaps I'll let you know when this is ready.

**Comment by prjemian** [comment]
This is the routine where the change should be made, just before the `return`:  https://github.com/aps-8id-trr/ipython-8idiuser/blob/17551de413684e47ede68ec06a47677e996b497c/profile_bluesky/startup/spec_support/APS_DM_8IDI.py#L154-L176

**Comment by prjemian** [comment]
**and** here, too, just before `suffix = 0`: https://github.com/aps-8id-trr/ipython-8idiuser/blob/17551de413684e47ede68ec06a47677e996b497c/user/ad_acquire.py#L79-L99

**Comment by prjemian** [comment]
Same place for both, just before `suffix = 0`.

**Comment by prjemian** [comment]
This is the [`cleanupText`]() function to use (it's for dictionary keys but will work for our file name if we use it on the base part of the file name, with no extension).

**Comment by prjemian** [comment]
Ok, this variation can be called with a full path to a directory name:

```
def cleanupFilename(text):
    """
    convert text so it can be used as a file name
    Given some input text string, return a clean version
    remove troublesome characters, perhaps other cleanup as well.
    This is best done with regular expression pattern matching.
    """
    path, base = os.path.split(text)
    base, ext = os.path.splitext(base)

    pattern = "[a-zA-Z0-9_]"

    def mapper(c):
        if re.match(pattern, c) is not None:
            return c
        return "_"

    base = "".join([mapper(c) for c in base])
    return os.path.join(path, base+ext)
```

**Comment by prjemian** [comment]
Works like this:

```
In [25]: cleanupFilename("/ bad $$ &^%%$ path with/good_file_name.txt")                                                                     
Out[25]: '/ bad $$ &^%%$ path with/good_file_name.txt'

In [26]: cleanupFilename("/good/path/to/bad file &^$*&^(&) name.txt")                                                                       
Out[26]: '/good/path/to/bad_file___________name.txt'
```

**Comment by prjemian** [comment]
@sureshnaps Do we need to clean up the file path, as well?

**Comment by sureshnaps** [comment]
@prjemian No, path should be fine as it is made by staff. Just filename.

**Comment by prjemian** [comment]
Thanks.  With assistance from @ericmdufresne, installed the fix at the beam line today and he restarted the helper.

**Comment by ericmdufresne** [comment]
Sorry to report that the fix didn't work.
In adding a single space, the DM server crashed again and it made it 
difficult to restart helper.py again. Qingteng figured out that we need to 
rerun the script calling DM with the fixed line without space, allow the 
script to stop at the broken DM service, then restart the server which 
works because the new queued name make sense.

The fix unfortunately didn't work.

Regards,
Eric

OSError: Unable to create file (unable to open file: name = '/home/8-id-i/2019-3/dufresne201911/A002_DirectBeamFocusedNoSample _021C_att0_Lq0_001/A002_DirectBeamFocusedNoSample__021C_att0_Lq0_001_0002_2000.hdf', errno = 2, error message = 'No such file or directory', flags = 15, o_flags = c2)

**Comment by prjemian** [comment]
So, that's a space between `Sample` and `_021C_att0`, like `Sample _021C_att0_Lq0_001`?  That's helpful since it means there is another place to be changed.  Thanks!

**Comment by sureshnaps** [comment]
@prjemian would it be easier if we use regexp to find the location of all the spaces and then rebuild the char without those.

**Comment by prjemian** [comment]
We *could* look through the whole path and replace but that has consequences for *path not found* errors.  Also, the calling code probably has a record of the path it stated.  We have to create clean names at the time we get the text from the PV.  The method today does this later, just before the file is written.  The caller needs to know whatever name is used since it might be written or reported elsewhere.

Will clean it up on Monday?

**Comment by prjemian** [comment]
@sureshnaps The code uses regexp to replace *any* character that is not *a-z*, *A-Z*, *0-9*, and `_`.  This line: https://github.com/aps-8id-trr/ipython-8idiuser/blob/5e3b20ecde56b89150047a46f3e2ff61089a590f/profile_bluesky/startup/spec_support/APS_DM_8IDI.py#L178

We could expand that to include `-`.  But we need to apply this earlier.  Easier to do when sitting at the beam line.

**Comment by sureshnaps** [comment]
@prjemian No rush, from now till Monday, there is no user, it is staff time. So this can be done when we meet on Monday.

**Comment by prjemian** [comment]
Good.  The most unfortunate situation is when the PV contains a `/` that was not intended to be a directory separator, just a mistake.  That's why we have to clean this up as soon as we get the text from the PV.
