### ISSUE TITLE
The "tab completion" bug has bit again

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#14]
In ipython, one can type the name of an object, then `.`, then press the <Tab> key to see a list of the object's attributes that could be typed at that point.  This aids auto-completion as one searches for a certain attribute.  Tab completion works for the first `.` but not for any after that.  Example, given motor `tth`, then `tth.user_readback.va<Tab>` should autocomplete with `value`, since this is the only attribute of `user_readback` which matches `va`.  No list appears and that's the bug.

**Comment by prjemian** [comment]
It's a well known problem, yet easily forgotten solution.  There is an [ipython issue](https://github.com/ipython/ipython/issues/11546#issuecomment-515680435) for this.

Summary:

> Disable Jedi. Just never ever use [jedi](https://github.com/davidhalter/jedi).

[Jedi](https://jedi.readthedocs.io/en/latest/) is *an awesome autocompletion/static analysis library for Python*. yet it is the problem to be removed.

For us, we should do this:

    conda activate bluesky
    conda uninstall jedi

That should fix the situation.

**Comment by prjemian** [comment]
As [another post suggests](), can start ipython (or jupyter) with an additional optional option:

    --IPCompleter.use_jedi=False

That would bring our ipython startup command sequence to:

    bash
    source /APSshare/anaconda/x86_64/bin/activate
    conda activate bluesky
    ipython --profile=bluesky --ipython-dir=~/.ipython-bluesky --IPCompleter.use_jedi=False

Way too much to remember.  We should make a shell script for this so the user sees a simpler command.

**Comment by prjemian** [comment]
Confirmed that this sequence fixes the problem.

```
In [1]: tth.user_<Tab>
user_offset user_offset_dir user_readback user_setpoint
In [1]: tth.user_re<Tab>
In [1]: tth.user_readback.<Tab>
In [1]: tth.user_readback.va<Tab>
In [1]: tth.user_readback.value
Out[1]: -4.2084

In [2]: tth.user_readback.value

```

**Comment by sureshnaps** [comment]
this is great, we will make a shell called bluesky8IDI similar to spec8IDI

**Comment by prjemian** [comment]
bluesky8IDI:

```
#!/bin/bash

source /APSshare/anaconda/x86_64/bin/activate
conda activate bluesky
ipython --profile=bluesky --ipython-dir=~/.ipython-bluesky --IPCompleter.use_jedi=False
```

**Comment by sureshnaps** [comment]
I have made a bluesky8IDI in ~/bin and copied the start up contents to it.
