### ISSUE TITLE
Create custom conda environment for 8ID

### ISSUE THREAD

**Issue by jkirchman** [aps-8id-trr/ipython-8idiuser#2]
create a custom conda environment, local to the 8ID workstation to 
insulate the beam line against unexpected changes in the /APSshare 
installation of bluesky.  There is some sensitivity to this at the beam 
line and we should try to be conservative here.

**Comment by prjemian** [comment]
first, check that there is not a conda environment already named `bluesky` with command:  `conda env list`

```
snow% which conda
/APSshare/anaconda/x86_64/bin/conda
snow% conda env list
# conda environments:
#
base                  *  /APSshare/anaconda/x86_64
                         /home/beams10/8IDIUSER/xicam2_py_VE
```

Good, we can proceed with commands to build and populate with BS

```
conda create -n bluesky python=3
```

you might get a warning that conda needs to be update on the server, that's ok for now

**Comment by prjemian** [comment]
This is a good time to add some conda *channels* (web sites with software) for our upcoming downloads and maintenance.  Here's what I have used elsewhere:

```
(base) jemian@wow ~ $ conda env list
# conda environments:
#
base                  *  /APSshare/anaconda/x86_64
apspy27                  /home/oxygen/JEMIAN/.conda/envs/apspy27
bluesky                  /home/oxygen/JEMIAN/.conda/envs/bluesky
pydm                     /home/oxygen/JEMIAN/.conda/envs/pydm
pymca_python3_qt5        /home/oxygen/JEMIAN/.conda/envs/pymca_python3_qt5

(base) jemian@wow ~ $ cat /home/oxygen/JEMIAN/.conda/envs/bluesky/.condarc 
channels:
  - prjemian
  - aps-anl-tag
  - aps-anl-dev
  - conda-forge
  - lightsource2-tag
  - lightsource2-dev
  - pydm-tag
  - pydm-dev
  - defaults
```

**Comment by prjemian** [comment]
install bluesky and friends, see what else comes along, create a requirements file and install from that:

```
bluesky
ophyd
databroker
event-model
apstools
ipython
jupyter
tornado<5
```

**Comment by prjemian** [comment]
command (using the requirements file from previous step)

    conda install --file requirements.txt

**Comment by prjemian** [comment]
Note in our requirements that the tornado package must be kept at the latest version *before* major version 5 (see https://github.com/ContinuumIO/anaconda-issues/issues/8789).  We imposed that at the installation but we want to keep it from being updated later.  We'll add a `pinned` file to our conda environment to maintain that rule for us during updates:

```
touch /home/beams/S8IDIUSER/.conda/envs/bluesky/conda-meta/pinned
# edit that file adding just this next line
tornado<5
```

**Comment by prjemian** [comment]
Now we can test if we have installed enough software to be useful.  Might still need more...

```
import apstools.devices as APS_devices
aps = APS_devices.ApsMachineParametersDevice(name="aps")
aps.current.read()
```

**Comment by prjemian** [comment]
Good, our initial tests showed that we forgot to install PyEpics.  That has been added to the requirements [above](https://github.com/aps-8id-trr/ipython-8idiuser/issues/2#issuecomment-509772904) now.

**Comment by prjemian** [comment]
@jkirchman See the new procedure at https://github.com/BCDA-APS/use_bluesky/blob/master/python_installation/environment.md

**Comment by jkirchman** [comment]
Done with this conda environment.
