### ISSUE TITLE
use newer ophyd support for Gather & Scatter

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#26]
There is new support for the Gather and Scatter area detector plugins.  Try using them instead of our own.

In Slack/Nikea, @tacaswell said:

> https://github.com/bluesky/ophyd/pull/688 includes attempts by @klauer to make supporting a range of AD versions managable as we now have classes for every plugin for every AD version where they change.

**Comment by prjemian** [comment]
Yikes!  Now throwing errors from `imm0`:

```
----> 1 adlambda.imm0.describe_configuration()

~/.conda/envs/bluesky/lib/python3.7/site-packages/ophyd/areadetector/plugins.py in describe_configuration(self)
    214
    215         source_plugin = self.source_plugin
--> 216         ret.update(source_plugin.describe_configuration())
    217
    218         return ret

AttributeError: 'NoneType' object has no attribute 'describe_configuration'

In [8]: adlambda.imm0.source_plugin

In [9]:
```

**Comment by prjemian** [comment]
Revert to our own local code until beam line lets us work with the lambda again.

**Comment by tacaswell** [comment]
@prjemian Can you push these classes into ophyd as soon as practical?

**Comment by prjemian** [comment]
Sure.  Sounds like a PR mid next week.  Ok?

**Comment by tacaswell** [comment]
That sounds great!

**Comment by prjemian** [comment]
Closing this for now since our local approach is not generating exceptions.

Will open new issue if the newer ophyd support for Gather & Scatter is to be use.

**Comment by sureshnaps** [comment]
@prjemian Since beam is down, we can work the rest of the week on Lambda.
