### ISSUE TITLE
pl_cnt function to enable plotting specific signals

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#28]
SPEC has a `plotselect` macro to define what gets plotted.  We [**need**](https://www.thebalance.com/wants-vs-needs-1388544) that.  Current situation of changing all the `.kind` attributes is way too much work.

**Comment by jkirchman** [comment]
@prjemian SPEC also allows the user to define the type of plot to be used. This is probably another item that should be put on the list of deliverables to users of Bluesky. Configurable plot items include logarithmic, show grid, size of point dots, scaling, and width of lines. Here is the output of the "setplot" utility:
```
     Use splot utility for plots? NO
      Program name for splot (SPLOT_PROGRAM)? ---
      Use more than one splot window for different counters? ---
    Use x11filt for plots? YES
      Use more than one x11filt window for different counters? NO
    Do ASCII plots? NO

    Do plots during scans? YES
     Raise plot window to top during scans? NO
     Auto scale x-axis during scans? YES
    Do plot after scan? YES
     Raise plot window to top at end of scan? YES

    Draw a background grid? ---
    Draw big dots? YES
     Dot size? ---
    Connect points with lines? YES
     Line width? ---
    Draw error bars? NO

    Use logarithmic y-axis? NO
    Force y-axis minimum to zero? NO
    Use logarithmic x-axis? NO
    Use background subtraction for plots? NO
     Number of points to average at each end? ---
```

**Comment by prjemian** [comment]
an APS-specific implementation at 8-ID-I

<details>
<summary><tt>plcounter.mac</tt></summary>
<p>

```
"""
Set a counter as detector to be plotted.

DESCRIPTION
===========
This is a utility which combines the functionalities of counters and 
plotselect. A counter is set as the detector and then plotted. 

LIMITATIONS
===========
None

Installation
============

Setup
-----
No special configuration is needed to run these macros. Simply load the macro
file::

  > qdo plcounter.mac

Dependencies
------------
There are no dependencies on other files, functions, or definitions.

Impact
------
 
N/A


File information
================

AUTHORS:

  * X. Jiao (XJ, jiaox), 
    Argonne National Laboratory
  * J Kirchman (JAK, jkirchman), 
    Argonne National Laboratory

CREATION DATE:

  2005-04-17

COPYRIGHT:

  .. automatically retrieve the current year:
  .. |current_year| date:: %Y

  Copyright (c) 2005-|current_year|, UChicago Argonne, LLC

  All Rights Reserved

  APS SPEC macros

  APS SPEC development team,
  X-ray Science Division and APS Engineering Support Division,
  Argonne National Laboratory

LICENSE::

  OPEN SOURCE LICENSE

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

  1. Redistributions of source code must retain the above copyright notice,
     this list of conditions and the following disclaimer.  Software changes,
     modifications, or derivative works, should be noted with comments and
     the author and organization's name.

  2. Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.

  3. Neither the names of UChicago Argonne, LLC or the Department of Energy
     nor the names of its contributors may be used to endorse or promote
     products derived from this software without specific prior written
     permission.

  4. The software and the end-user documentation included with the
     redistribution, if any, must include the following acknowledgment:

     "This product includes software produced by UChicago Argonne, LLC
     under Contract No. DE-AC02-06CH11357 with the Department of Energy."

  *****************************************************************************
  *****************************************************************************

  DISCLAIMER

  THE SOFTWARE IS SUPPLIED "AS IS" WITHOUT WARRANTY OF ANY KIND.

  Neither the United States GOVERNMENT, nor the United States Department
  of Energy, NOR uchicago argonne, LLC, nor any of their employees, makes
  any warranty, express or implied, or assumes any legal liability or
  responsibility for the accuracy, completeness, or usefulness of any
  information, data, apparatus, product, or process disclosed, or
  represents that its use would not infringe privately owned rights.

  *****************************************************************************

VERSION::

  $Revision: 679 $
  $Date: 2013-04-23 13:39:41 -0500 (Tue, 23 Apr 2013) $
  $Author: jkirchman $
  $URL: https://subversion.xray.aps.anl.gov/spec/common/bcda/plcounter.mac $

CHANGE LOG:

  2005-04-17 (XJ):

  - original

  2012-03-01 (JAK):

  - add documentation compatible with the specdomain for Sphinx.
  
"""

#------------------------------------------------------------------------------
def plcounter '{
  """
  Set a counter as detector and plot results. Interactive mode is used if 
  no counter is provided. 

  USAGE::

    > plcounter [<cnt>]

  ARGUMENTS:

    :cnt: Name, mnemonic, or number of the counter [str/int]

  EXAMPLES::

    > plcounter ccdc

    > plcounter 3
   

  """

    if ($# >1) {
       p "Usage: plcounter or plcounter counter_mne"
       exit
    }
    local s  v i
    s = DET;
    if($#==1) 
       DET = cnt_num($1);
    if( $# ==0) {
       _show_cntr;
       DET = cnt_num(v = getval("Counter number for detector", s))
    }    
    if (DET < 0 || DET >= COUNTERS) {
       printf("Channel %s invalid for detector.\n", v)
       DET = s
       exit
    }
    _plotconfig();
    PLOT_NUM = 1
    PLOT_SEL["0"] = cnt_mne(DET)

    
    PL_Y=plotlist();
    printf("\ncounter \"%s\" is selected as detector and will be plotted.\n", cnt_mne(DET))
} '
```

</p>
</details>

**Comment by prjemian** [comment]
* [`plot_cntl(cmd)`](https://certif.com/spec_manual/ref_2_4_6.html#kwdidx_802)
* [plotting options](https://certif.com/spec_manual/mac_3_7.html#kwdidx_1147)

**Comment by prjemian** [comment]
The *ophyd* `ScalerCH` scaler object we use for scaler support has a [`select_channels()`](https://github.com/bluesky/ophyd/blob/40d4b6ab8e08b5aeb2b8228fbf76d7d6b2181337/ophyd/scaler.py#L123-L133) method that provides this capability.  (It modifies the `hinted` attribute of each scaler channel accordingly.)

**Comment by prjemian** [comment]
To plot specific signals, such as scaler channels, use the python objects for those signals as part of the list of detectors.  Define a convenience shortcut if the path to any signal is too cumbersome to use.

For example, the scaler channels are buried a couple levels under the scaler object.  It is a challenge to remember all the structure of that object.  Since the channels are pre-assigned and rarely change (due to hardware wiring), we create shortcuts to the important ones at the global level.  https://github.com/aps-8id-trr/ipython-8idiuser/blob/22167e3066da7f705169eb0206f5b3740d3f0c3e/profile_bluesky/startup/20-detectors.py#L40-L51

To use only a few of these, or even just one, put the desired object(s) in the list of detectors where you would have put `scaler1`.  Examples:

    RE(bp.count([pind4, I0Mon]))
    RE(bp.rel_scan([pind1], motor, -1, 1, 21))

**Comment by prjemian** [comment]
> 
> 
> @prjemian SPEC also allows the user to define the type of plot to be used. This is probably another item that should be put on the list of deliverables to users of Bluesky. Configurable plot items include logarithmic, show grid, size of point dots, scaling, and width of lines. Here is the output of the "setplot" utility:
> 
> ```
>      Use splot utility for plots? NO
>       Program name for splot (SPLOT_PROGRAM)? ---
>       Use more than one splot window for different counters? ---
>     Use x11filt for plots? YES
>       Use more than one x11filt window for different counters? NO
>     Do ASCII plots? NO
> 
>     Do plots during scans? YES
>      Raise plot window to top during scans? NO
>      Auto scale x-axis during scans? YES
>     Do plot after scan? YES
>      Raise plot window to top at end of scan? YES
> 
>     Draw a background grid? ---
>     Draw big dots? YES
>      Dot size? ---
>     Connect points with lines? YES
>      Line width? ---
>     Draw error bars? NO
> 
>     Use logarithmic y-axis? NO
>     Force y-axis minimum to zero? NO
>     Use logarithmic x-axis? NO
>     Use background subtraction for plots? NO
>      Number of points to average at each end? ---
> ```

This is good content for a new issue.  It may be only a problem of *where is the documentation* rather than *unimplemented features*, since I believe the capabilities are all available through the MatPlotLib infrastructure.

**Comment by prjemian** [comment]
For example, in my view, I *really* want each data point to have a symbol.  The default is no symbol, just lines connecting data points.
