### ISSUE TITLE
Bluesky can't start after adding ad_lambda2M 

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-trr/ipython-8idiuser#289]
Bluesky can't connect to `8idLambda2mHDF1:CreateDirectory_RBV`. The output from terminal is attached. The code on 150-Lambda2M is up-to-date.

[Output_Terminal.txt](https://github.com/aps-8id-dys/ipython-8idiuser/files/8783124/Output_Terminal.txt)

**Comment by prjemian** [comment]
Does this PV exist?
8idLambda2mHDF1:CreateDirectory_RBV

**Comment by qzhang234** [comment]
@prjemian Sorry, that wasn't the issue, I forgot to add `:` after 8idLambda2m`. Now Bluesky starts fine.

Closing the issue
