### ISSUE TITLE
prefer logging to print 

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#3]
As stated [elsewhere](https://github.com/BCDA-APS/use_bluesky/issues/40), prefer to use `logger.info()` (or `logger.warning()` or error or debug or critical) instead of `print()`.

see:

* https://stackoverflow.com/questions/6918493/in-python-why-use-logging-instead-of-print
* https://www.loggly.com/blog/4-reasons-a-python-logging-library-is-much-better-than-putting-print-statements-everywhere/

Quoting the latter:

> The Python logging library lets you:
> 
> *   Control what’s emitted
> *   Define what types of information you want to include in your logs
> *   Configure how it looks when it’s emitted
> *   Most importantly, set the destination for your logs

**Comment by prjemian** [comment]
Basically, this involves changing instances of `print()` to `logger.info()` in every startup .py file **after** `00-logging.py` (where `logger` is defined).

See comparable changes in the [`use_bluesky`](https://github.com/BCDA-APS/use_bluesky/commit/f5d74be508db337f73acf44dac7ac643b7f8b2eb) repository.

**Comment by jkirchman** [comment]
There are several 00-*.py files. It is unclear whether these are invoked after or before `00-logging.py`. The [use_bluesky] repository only updates `00-startup.py`.

-rw-rw-r-- 1 8idiuser s8staff 1195 Jul 10 16:47 00-0-checks.py
-rw-rw-r-- 1 8idiuser s8staff 1931 Jul 10 16:47 00-logging.py
-rw-rw-r-- 1 8idiuser s8staff  801 Jul 10 16:47 00-startup-jup.py
-rw-rw-r-- 1 8idiuser s8staff  756 Jul 10 16:47 00-startup.py

**Comment by prjemian** [comment]
The files in startup are invoked alphabetically.  See the [README.md](https://github.com/BCDA-APS/use_bluesky/blob/master/ipython_setup/startup/README.md) (original) for an explanation.

The [changeset referenced](https://github.com/BCDA-APS/use_bluesky/commit/f5d74be508db337f73acf44dac7ac643b7f8b2eb) shows 12 files changed.

You can delete ` 00-startup-jup.py`.  We won't use it.

**Comment by prjemian** [comment]
Also, the order those files are invoked is exposed as a bluesky session is started.

**Comment by jkirchman** [comment]
Also, the file `80-callbacks.py` has two print lines (in def newSpecFile) which were not modified with logger.info. Was this intended or just an oversight?
``` 
print(f"SPEC file name : {specwriter.spec_filename}")
print(f"File will be {handled} at end of next bluesky scan.")
```

**Comment by jkirchman** [comment]
There seems to be no 21-signals.py. Did this get removed?

**Comment by prjemian** [comment]
More oversight than intent.  The intent is to move this code to apstools but the code needs access to the user's `specwriter` object and I've yet to figure out a way to do that from the `apstools` package.  (Probably can do that if I create a function the user will call to *register* their `specwriter` instance.)

**Comment by prjemian** [comment]
Hmmm... no `21-signals.py` ...  Since we have not yet done *anything* with these `startup/*.py` files, let's delete them and update with newer version from `use_bluesky`.

**Comment by prjemian** [comment]
Note that `21-signals.py` exists in the `use_bluesky` repository.  Just [updated `use_bluesky`](https://github.com/BCDA-APS/use_bluesky/commit/0efb04b1449268eb6382686950a028816cf54336) per [Jeff's comment](https://github.com/aps-8id-trr/ipython-8idiuser/issues/3#issuecomment-510513639).

**Comment by prjemian** [comment]
deleting and re-installing the new versions

```
cd ~/.ipython-bluesky/profile_bluesky/
/bin/rm -rf startup
pushd /tmp/use_bluesky/ipython_setup
git pull
tar cf - startup | (cd ~/.ipython-bluesky/profile_bluesky/ && tar xvf -)
popd
```

**Comment by prjemian** [comment]
that closes this issue
