### ISSUE TITLE
subclass EpicsSignal for batch_pars items

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#31]
As part of #25, create a subclass of `ophyd.EpicsSignal` for the items of the `batch_pars` list used in SPEC now.  Need additional terms for `label`, `h5address`, maybe some others, too.  That's a start.

**Comment by sureshnaps** [comment]
If possible without a lot of work, if there is a code that would work by making the current implementation faster without using bluesky, then we can start using that right away. Basically, a faster version of Create_Metadata.py

**Comment by prjemian** [comment]
I think that might be more work.  But I'll look this over before starting implementation.

**Comment by sureshnaps** [comment]
Thanks. If it is too much extra work, then it is not worth it. What I had planned in the interim to make it faster was to write a .json file from all the epics pvs that spec writes to the registers and then I can call the create_metadata asynchronously and make it as a stage in the DM. So this will not delay the next data acquisition. If you think this is an ok approach, then I can do that.

**Comment by prjemian** [comment]
That would be faster

**Comment by sureshnaps** [comment]
ok i will work on that.
