### ISSUE TITLE
First Macro (Plan) in Bluesky: Operation of Rigaku Detector

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-trr/ipython-8idiuser#37]
It appears that setting up the capacity for running 'plans' ('macros' in SPEC) in Bluesky is essential for user operation. One of the most important macros is the data acquisition macro, which:

1. Acquire a set of frames with the area detector; 
2. Collects metadata from EPICS; 
3. Submit the frame set and metadata and start the workflow on cluster nodes. 

For now we'll focus on the R&D Rigaku detector instead of Lambda because the operation of Rigaku detector is simpler. 

I have attached the file 'Rigaku_Bluesky.do' that performs all three operations. Since this looks way too complicated, I propose that we start from step 1 (acquisition) and build our way up. The file 'Rigaku_Bluesky_Acq.do' does only the acquisition. It requires:

1. epics_put:
2. epics_get:
3. sleep( ), equivalent to time.sleep( ) in module 'time' 
4. printf, print to screen.

Shall we set up the environment for Bluesky Plans, then take a look at 'Rigaku_Bluesky_Acq.do' and decide what is the best practice for epics_put/get and printf in this scenario?

Thanks,

QZ

[Rigaku_Bluesky_Acq.txt](https://github.com/aps-8id-trr/ipython-8idiuser/files/3547916/Rigaku_Bluesky_Acq.txt)
[Rigaku_Bluesky.txt](https://github.com/aps-8id-trr/ipython-8idiuser/files/3547917/Rigaku_Bluesky.txt)

**Comment by prjemian** [comment]
@qzhang234 : Great progress today.  We made an ophyd Device and then a bluesky plan and together, they worked talking with the Rigaku detector simulator.  Nice.

If you deposit the bluesky `.py` file from today (drop it into this issue), then this issue can be closed.

**Comment by qzhang234** [comment]
@prjemian 

The .py file is attached (had to change it into a .txt because github doesn't like .py). 

There are still some of those unresolved block codes
[Rigaku_Acq.txt](https://github.com/aps-8id-trr/ipython-8idiuser/files/3557597/Rigaku_Acq.txt)
, but should we move it to another issue?

**Comment by prjemian** [comment]
<details>
<summary>Rigaku_Acq.py</summary>
<p>

```
# get all the symbols from the IPython shell
import IPython
globals().update(IPython.get_ipython().user_ns)
logger.info(__file__)

import subprocess 
import datetime


class UFXC_Device(Device):
    shutter_control = Component(EpicsSignal, "8idi:softGlueC:AND-4_IN2_Signal")
    acquire_start = Component(EpicsSignal, "8idi:Unidig2Bo7.VAL")
    acquire_complete = Component(EpicsSignal, "8idi:Unidig2Bi2.VAL")

UFXC = UFXC_Device(name = "UFXC")


def unix(command):
    # TODO: use logging package
    sp = subprocess.Popen(
        command, 
        shell=True,
        stdin = subprocess.PIPE,
        stdout = subprocess.PIPE,
        stderr = subprocess.PIPE,
        )
    out, err = sp.communicate()
    return out


def UFXC_Acquire(batch_name = 'A001_Test'):

    yield from bps.mv(UFXC.shutter_control, 'UFXC')
    cmd = f"echo FILE:F:{batch_name} | nc 164.54.116.83 10000"
    exitcode = unix(cmd)    # FIXME: blocking code!!!
    # If exitcode not equal b'', then an error has occurred
    print(f"START of UFXC Measurement: {datetime.datetime.now()}")

    yield from bps.mv(UFXC.acquire_start, 1)
    yield from bps.sleep(0.1)
    yield from bps.mv(UFXC.acquire_start, 0)
       
    yield from bps.sleep(0.2)

    print("Waiting for UFXC to finish DAQ and ready for next Daq")

    while UFXC.acquire_complete.get() not in (1, 'High'):
        yield from bps.sleep(0.01)  # FIXME: use a status object instead
    print(f"UFXC is ready to start the next DAQ: {UFXC.acquire_complete.value}")

    print(f"END of UFXC Measurement: {datetime.datetime.now()}")
```

</p>
</details>

**Comment by prjemian** [comment]
The unresolved block codes (`TODO:` and `FIXME:`) are good for an additional lesson that shows how to start and wait for asynchronous processes such as this one.
