### ISSUE TITLE
Generate Rigaku Metadata & Test DM Workflow 

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-trr/ipython-8idiuser#39]
Now that we can control the UHSS Labview software, I think we can now move on to generating the metadata and start the DM Workflow. I have attached the files relevant for this process that we need to translate into bluesky.

@sureshnaps Am I right in that, for the Rigaku workflow: 
1. SPEC macro first calls 'write_RIGAKU_batch_pars' to manually write the variables into dictionary file 'batch_pars';
2. 'finish_set' calls 'writebatchinfo' and fills the rest of 'batch_pars' from EPICS PV;
3. 'finish_set' calls 'write_CCD_Metadata_Registers' that passes 'batch_pars' to string registers and 'write_CCD_MetaData_Registers' creates the metadata file ('hdf') to be sent to DM Workflow?

@prjemian @sureshnaps 
Which of the four steps do we already have a bluesky script for? Which of them need to be rewritten? And which of them can be used for Lambda as well?

@ericmdufresne @sureshnaps 
When is a good time to mount the Rigaku detector and make sure it can take images at ~ 3 s gap time (need to synchronize with Nakaye)?

[write_CCD_MetaData_hdf.txt](https://github.com/aps-8id-trr/ipython-8idiuser/files/3557654/write_CCD_MetaData_hdf.txt)
[finish_set.txt](https://github.com/aps-8id-trr/ipython-8idiuser/files/3557655/finish_set.txt)
[writebatchinfo.txt](https://github.com/aps-8id-trr/ipython-8idiuser/files/3557656/writebatchinfo.txt)
[write_CCD_MetaData_Registers.txt](https://github.com/aps-8id-trr/ipython-8idiuser/files/3557657/write_CCD_MetaData_Registers.txt)
[write_RIGAKU_batch_pars.txt](https://github.com/aps-8id-trr/ipython-8idiuser/files/3557658/write_RIGAKU_batch_pars.txt)

**Comment by sureshnaps** [comment]
@qzhang234 the sequence is correct. We can mount RIgaku next Tuesday.

**Comment by prjemian** [comment]
Once #36 is complete and merged (via #76), we can finish this up.  We've already tested the DM workflow from bluesky and then from the linux command line (with the tool that SPEC will use from now on).  We need confirmation tests from both SPEC and bluesky that both are ready to use the APS Data Management tools with our final edit of the shared tools to initiate that workflow.

**Comment by prjemian** [comment]
With bluesky, we have already built the code comparable to `write_CCD_Metadata_Registers` (named `staging_setup_DM`) for the Lambda detector.  We'll do similar for the Rigaku.  This code is not identical since at least some of the information comes from different places.  All part of the design.  Each detector should know how to write this *for that detector*.  Each detector will have its own method, `staging_setup_DM()`, that customizes this step.  This enables a more generic acquisition plan that knows the general steps, leaving details to each device.

**Comment by prjemian** [comment]
For the Lambda, this looks like:

```
    def staging_setup_DM(self, *args, **kwargs):
        """
        setup the detector's stage_sigs for acquisition with the DM workflow
        
        Implement this method in _any_ Device that requires custom
        setup for the DM workflow.
        """
        assert len(args) == 5
        file_path = args[0]
        file_name = args[1]
        num_images = args[2]
        acquire_time = args[3]
        acquire_period = args[4]

        self.cam.stage_sigs["num_images"] = num_images
        self.cam.stage_sigs["acquire_time"] = acquire_time
        self.cam.stage_sigs["acquire_period"] = acquire_period
        self.immout.stage_sigs["enable"] = 1
        self.immout.stage_sigs["blocking_callbacks"] = "Yes"
        self.immout.stage_sigs["parent.cam.array_callbacks"] = 1
        self.immout.stage_sigs["file_path"] = file_path
        self.immout.stage_sigs["file_name"] = file_name
        self.immout.stage_sigs["num_capture"] = num_images
        self.immout.stage_sigs["file_number"] = 1
        self.immout.stage_sigs["file_format"] = "IMM_Cmprs"
        self.immout.stage_sigs["capture"] = 1
```

The Rigaku suport *must* be different since it does not use EPICS area detecotr and does not have a plugin chain with `immout` (among others).  The metadata will come from somewhere else.

**Comment by prjemian** [comment]
CORRECTION, my comments above are setup for taking an image.  Writing of the metadata registers is done from the generic data acquisition methods `AD_Acquire.update_metadata_prescan()` (before the detector takes an image) and `AD_Acquire.update_metadata_postscan()` (after the image taking).

**Comment by prjemian** [comment]
We have python/bluesky code that reads the `detectorinfo.m` file (Matlab) with the detector parameters and that is the info that is written to the EPICS PV registers.  Our matlab file needs to be updated with the new detector (46, in this case).  Mostly good to go then.

**Comment by prjemian** [comment]
The rigaku detector was made to look like a bluesky detector in issue #40.  We'll just add the additional methods we call from the generic work flow so this Rigaku does not have to **be** an EPICS area detector.

**Comment by prjemian** [comment]
ready to test our acquisition with the Rigaku

```
In [1]: %run -m ad_acquire                                                                                                                                                                         
I 2019-09-27 12:58:22.936 - /home/beams/8IDIUSER/.ipython-bluesky/user/ad_acquire.py

In [2]: RE(AD_Acquire(rigaku, submit_xpcs_job=True, file_name="A123"))                                                                                                                             
```

Workflow runs and fails, no metadata file written some PV write times out.  Additing diagnostics to identify failure point.

**Comment by prjemian** [comment]
Long exception trace.  Pulling out fragments:

```
/home/beams/8IDIUSER/.conda/envs/bluesky/lib/python3.7/site-packages/epics/ca.py:1459: UserWarning: ca.get('8idi:Reg169') timed out after 1.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
...
~/.ipython-bluesky/user/ad_acquire.py in update_metadata_postscan()
    178         )
    179         yield from bps.mv(
--> 180             dm_pars.scan_id, int(RE.md["scan_id"]),
    181         )
    182 
...
FailedStatus: Status(obj=EpicsSignal(read_pv='8idi:Reg169', name='dm_pars_scan_id', parent='dm_pars', value='100', timestamp=1569607122.832141, auto_monitor=False, string=True, write_pv='8idi:Reg169', limits=False, put_complete=False), done=True, success=False)
```

**Comment by prjemian** [comment]
There's a hard-coded path in the HDF5 metadata file path.  Let's fix that one.

**Comment by prjemian** [comment]
@sureshnaps :  How should we get the correct folder name here?  (hard coded for now)

```
    path = f"/home/8-id-i/{aps_cycle}/jemian_201908"        # FIXME: ?jemian_201908?
```

**Comment by prjemian** [comment]
now fails with:

```
        msg = plan_stack[-1].send(ret)
      File "/home/beams/8IDIUSER/.ipython-bluesky/user/ad_acquire.py", line 208, in inner
        hdf_with_fullpath, as_bluesky_plan=True)
    TypeError: 'NoneType' object is not iterable
```

**Comment by prjemian** [comment]
```
~/.ipython-bluesky/user/ad_acquire.py in inner()
    206 
    207         yield from dm_workflow.create_hdf5_file(
--> 208             hdf_with_fullpath, as_bluesky_plan=True)
    209 
    210         # no need to yield from since the function is not a plan

TypeError: 'NoneType' object is not iterable
```

**Comment by qzhang234** [comment]
@sureshnaps Also we currently don't know how to grab the detector number from the string registers so we hard-coded it into the detector class:

```
class Lambda750kAreaDetector(SingleTrigger, AreaDetector): 
    cam = ADComponent(Lambda750kCam, "cam1:")
    image = Component(ImagePlugin, suffix="image1:")
    #hdf1 = Component(
    #    Plugin_HDF5_EPICS_Names,
    #    suffix='HDF1:', 
    #    root = DATABROKER_ROOT_PATH,
    #    write_path_template = AD_HDF5_IOC_WRITE_PATH,
    #    read_path_template = AD_HDF5_DB_READ_PATH,
    #)
    immjoin = Component(ImmJoinPlugin, "IMMJoin:")
    imm0 = Component(IMMFilePlugin, "IMM0:")
    imm1 = Component(IMMFilePlugin, "IMM1:")
    imm2 = Component(IMMFilePlugin, "IMM2:")
    imm3 = Component(IMMFilePlugin, "IMM3:")
    immout = Component(IMMFilePlugin, "IMMout:")
    gather = Component(GatherPlugin, "Gather1:")
    scatter = Component(ScatterPlugin, "Scatter1:")

    detector_number = 25    # 8-ID-I numbering of this detector

```

**Comment by qzhang234** [comment]
@prjemian Would you have some time on Monday to test the Rigaku workflow in SPEC with @sureshnaps ?

**Comment by prjemian** [comment]
I'll have a better idea of my Monday schedule on Monday morning.  It's possible but that is the best interaction time I have with the other bluesky team members.

**Comment by sureshnaps** [comment]
now root_folder seem to have data_folder in it, not sure if this happened for rigaku or it has changed for lambda as well?

**Comment by prjemian** [comment]
This is working as we have tested it at the beam line.
