### ISSUE TITLE
spec2nexus : problem with conda package

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#4]
see https://github.com/prjemian/spec2nexus/issues/166

It seems the conda package is missing content necessary to parse SPEC data files.  This is a new bug.  Check the local installation (conda environment).  If found problematic:

    conda uninstall spec2nexus
    conda install matplotlib   # if this was uninstalled by previous command
    pip install spec2nexus

**Comment by jkirchman** [comment]
When performing the uninstall of spec2nexus, another package was removed as well. Should apstools be re-installed? 
```
The following packages will be REMOVED:

  apstools-1.1.7-py_0
  spec2nexus-2020.0.0-pyh39e3cac_0

Proceed ([y]/n)? y
```

**Comment by prjemian** [comment]
Yes, but *after* spec2nexus is installed by pip

**Comment by jkirchman** [comment]
It appears the install of apstools upgraded the version of spec2nexus installed by pip. Not sure if this is a problem. 
`
(bluesky) [8idiuser@snow startup]$ conda install apstools
. . .
The following NEW packages will be INSTALLED:

apstools aps-anl-tag/noarch::apstools-1.1.7-py_0
spec2nexus aps-anl-tag/noarch::spec2nexus-2020.0.2-h39e3cac_0

Proceed ([y]/n)? y
`

**Comment by prjemian** [comment]
Looks good to me.  I'll let you know when spec2nexus is fixed.
