### ISSUE TITLE
refactor Rigaku as Device similar to area detector

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#40]
Some controls require an operation that runs for a long time before returning a result.  If run from the main execution thread, this could **block** any and all other activities (such as data collection from other streams) before the operation returns.  One such operation is shown in #37 to trigger the Rigaku detector.  We wrote a *quick & dirty* [plan](https://github.com/aps-8id-trr/ipython-8idiuser/issues/37#issuecomment-526423932) to demonstrate how bluesky could communicate with that detector.

Another example is to open or close a shutter.  Since it is a mechanical device, the execution time may vary between operations.

Now, refactor the `Rigaku_Acq.py` code with an ophyd [Status Object](https://blueskyproject.io/ophyd/status.html?highlight=devicestatus#module-ophyd.status) that will run the blocking operation in a separate thread and signal the main thread when it is complete.  A few more steps are necessary but the advantages are that other data collection activities can continue, the RunEngine can continue to watch for suspenders that can trigger operations to pause, and we can add features such as imposing a timeout interval on the long operation. 

An example is in the *apstools* [`ShutterBase`](https://apstools.readthedocs.io/en/latest/source/_devices.html#apstools.devices.ShutterBase) class, in the [`.set()`](https://apstools.readthedocs.io/en/latest/_modules/apstools/devices.html#ShutterBase.set) operation.  Pay particular attention to how the [`DeviceStatus`](https://blueskyproject.io/ophyd/generated/ophyd.status.DeviceStatus.html?highlight=devicestatus) object is handled.

Hint: In `Rigaku_Acq.py`, the `UFXC_Device()` class can have a `set()` method where this is implemented.  As a result, the `UFXC_Acquire()` plan will need to be rewritten, much more simply, too.

Also, this code:

    yield from bps.mv(UFXC.acquire_start, 1)
    yield from bps.sleep(0.1)
    yield from bps.mv(UFXC.acquire_start, 0)

could be implemented as a modification to the `acquire_start` signal by overriding the `.set()` method.  That way, the pattern of *set, short wait, unset* would always be used.

**Comment by prjemian** [comment]
@KedoKudo, @Jasonzhouquan -- Would either of you like to sit in when we modify Bluesky support to control a blocking operation and allow the RunEngine to operate while the slow routine completes?

**Comment by KedoKudo** [comment]
@prjemian when will this coding session take place?  I would like to join if time permits.

**Comment by prjemian** [comment]
Next week when we are available.  These are your neighbors at 8-ID-I

**Comment by KedoKudo** [comment]
excellent, I'm looking forward to it 😄

**Comment by Jasonzhouquan** [comment]
I’ll be there if time permits. Thanks for the notice!

Regards,
Jason

**Comment by prjemian** [comment]
Wed, 9/19, 10 am at 8-ID-I
