### ISSUE TITLE
dm-support : writing to epics registers

### ISSUE THREAD

**Issue by sureshnaps** [aps-8id-trr/ipython-8idiuser#44]
@prjemian I am reviewing the DM commands to run to generate the metadata. It seems like we are missing the spec macro equivalent `write_CCD_MetaData_Registers` which fills in some of the registers.

***one step missing here before the 2 below***

    dm_pars = DataManagementMetadata(name="dm_pars")
    dm_workflow = APS_DM_8IDI.DM_Workflow(dm_pars)

**Comment by qzhang234** [comment]
This is a dumb question, but I can't seem to view the content of 'DataManagementMetadata' using '??' (It produces the same screen output as '?'. By the way I can view the contents of APS_DM_8IDI.DM_Workflow with '??' just fine). 

Is the definition of 'DataManagementMetadata' in one of the start-up python scripts? And does it take the name of the frame set generated by Lambda as the input?

**Comment by prjemian** [comment]
Interesting question.  The definition is in the startup/35-DM-support.py file.  Looks like it is all configuration and no code of its own.  So, nothing for `??` to display.  New to me.

**Comment by prjemian** [comment]
Actually, the equivalent of SPEC's `write_CCD_MetaData_Registers` is the `DataManagementMetadata()` class.  When the code does a put to any of the signals, that will do the EPICS caput() to the related PV.

The Python code we write should never need to call caput() directly.  We make EpicsSignal objects and write to them in our code (calling `yield from bps.mv(object, value)`).

**Comment by sureshnaps** [comment]
I still do not get it. Something is missing. For example, we did take some datasets but the epics registers still have the values from the last week of the run. When we take a new data, there has to be a code that updates the registers after which we can call
dm_pars = DataManagementMetadata(name="dm_pars")

**Comment by prjemian** [comment]
Agreed.  We'll need to add code to write that info.

**Comment by sureshnaps** [comment]
this is also related to #45 
is this something that @prjemian will do? I am trying to find things that we can do. I will work on the shutter, etc

**Comment by qzhang234** [comment]
Please let me know if there's anything I can do to help too
________________________________
