### ISSUE TITLE
select_detector macros

### ISSUE THREAD

**Issue by sureshnaps** [aps-8id-trr/ipython-8idiuser#45]
Since we have more than 1 detector, we have spec macros under
~8idiuser/local_macros/CCD_macros/multi_ccd_config_8idi.mac
where we might only need select_LAMBDA and select_RIGAKU, these are small relatively. 

Then, there are beam_params_backup and beam_params_restore under
~8idiuser/local_macros/CCD_macros/beamparams_8idi.mac

Now we are really going through the rabbit hole.

**Comment by prjemian** [comment]
That's  [*wabbit*](https://www.youtube.com/watch?v=GsavMPRua9Y)

**Comment by prjemian** [comment]
This file, `~8idiuser/local_macros/CCD_macros/beamparams_8idi.mac`, does not exist.  However, there are these two files with similar names:

* `/home/beams/8IDIUSER/local_macros/CCD_macros/beamparams_backup_restore_8idi.mac`
* `/home/beams/8IDIUSER/local_macros/CCD_macros/beamparams_registers_default_8idi.mac`

**Comment by prjemian** [comment]
The two macros, `beam_params_backup` and `beam_params_restore`, are in this file: `/home/beams/8IDIUSER/local_macros/CCD_macros/beamparams_backup_restore_8idi.mac:`

**Comment by sureshnaps** [comment]
@prjemian please disregard the file /home/beams/8IDIUSER/local_macros/CCD_macros/beamparams_registers_default_8idi.mac
that is a legacy file.

**Comment by prjemian** [comment]
OK

**Comment by prjemian** [comment]
tested existing support today, satisfied

not closing since TODO items still remain, moving to next milestone

**Comment by prjemian** [comment]
TODO items:

https://github.com/aps-8id-trr/ipython-8idiuser/blob/007747e3076b001d324a26d455318b727be6358e/profile_bluesky/startup/50-controls.py#L511-L513

https://github.com/aps-8id-trr/ipython-8idiuser/blob/007747e3076b001d324a26d455318b727be6358e/profile_bluesky/startup/50-controls.py#L553-L555

These are related and describe a base class : subclass structure where the subclasses are specific for each detector.  That's an example of when direct translation from SPEC (a procedural language) is better replaced by an object structure.

**Comment by prjemian** [comment]
Opened new issue #107 to finish the remaining work (which seems independent of this issue).
