### ISSUE TITLE
gitk credentials show Faisal Khan

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#5]
Others will commit from this beam line account.  We need to be able to change this.

**Comment by jkirchman** [comment]
I found the problem. There exists a credentials file for git:
```
(bluesky) [8idiuser@snow startup]$ cat ~/.gitconfig
[user]
        name = Faisal Khan
        email = fkhan@anl.gov
```
I'm inclined to delete the file.

**Comment by prjemian** [comment]
Let's put him into this conversation, so he knows about us and our plans.  I'll email him.

**Comment by n-log-n** [comment]
@prjemian @jkirchman I typically don't commit from that machine and probably did it only once. So please go ahead and delete my credentials. I am not sure if Suresh (the other user on that machine) use it to commit stuff.

**Comment by prjemian** [comment]
Would not have guessed your GH name: synonym for *n!*

**Comment by jkirchman** [comment]
Deleted credential file.
