### ISSUE TITLE
identify the slit components in 15-spec-config.py

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#55]
There are signals for the components of at least 6 sets of slits in startup file [`15-spec-config.py`](https://github.com/aps-8id-trr/ipython-8idiuser/blob/b02826dbdabdf0752a3034fb9c73c28cacb8f941/profile_bluesky/startup/15-spec-config.py).

Organize these into devices with common names (such `top`, `gap`, `center`, ...) so all slits will share the same spelling and use of common terms.  Not all slits have the same number of components defined by EpicsSignals.  That's OK.  We might need multiple devices defined as structures to be used.

Presumably, then, we'll have these slit objects:

* [x] sa1: 8ida:Slit1...
* [ ]  si1: 8idi:Slit1...
* [ ]  si2: 8idi:Slit2...
* [ ]  si3: 8idi:Slit3...
* [ ]  si4: 8idi:Slit4...
* [ ]  si6:  8idi:m41, 42, ...
* [ ]  si5:  8idi:m55, 56, ...

Do this work in a branch and then submit a Pull Request for review.

**Comment by qzhang234** [comment]
did not do si6
added sipink (not a replacement for si6, though)
