### ISSUE TITLE
resolve TODO & FIXME items in user/Lambda.py

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#61]
See items in the source code file marked `TODO:` or `FIXME:` (per #54)

**Comment by prjemian** [comment]
Also, give this file a [generic](https://github.com/aps-8id-trr/ipython-8idiuser/pull/54#issuecomment-528881695) name.

**Comment by prjemian** [comment]
Last TODO items are here: https://github.com/aps-8id-trr/ipython-8idiuser/blob/178ae0a9d51c5d1a16eeeba4b3dd4db0b6fb2657/user/Lambda.py#L121-L128

**Comment by sureshnaps** [comment]
The one TODO

**Comment by sureshnaps** [comment]
Sorry, closed by mistake. I thought the TODO was for me to do but realized it is not.

**Comment by prjemian** [comment]
Will leave these lines as-is for now: https://github.com/aps-8id-trr/ipython-8idiuser/blob/b9d28f3107cd693a377a4ad7adec6a4ae0791fdf/user/ad_acquire.py#L133-L135

**Comment by prjemian** [comment]
and this: https://github.com/aps-8id-trr/ipython-8idiuser/blob/b9d28f3107cd693a377a4ad7adec6a4ae0791fdf/user/ad_acquire.py#L192

**Comment by prjemian** [comment]
good enough for now
