### ISSUE TITLE
rename dm_pars to registers

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#77]
In #36, the EPICS PVs that hold metadata about the current measurement (so called *string resgisters*) are contained in an object named `dm_pars`.

It is proposed to change `dm_pars` to `registers` throughout the code base, as this new name seems more representative (needs no explanation when looking at the code, for example).

@sureshnaps , @qzhang234 : Agree?

**Comment by sureshnaps** [comment]
@prjemian i agree. The use of "dm" for all these things was bothering me. It is a great move. Except for the command that invokes the workflow, nothing in SPEC is now called "dm". It would be good to keep the same way.
The class or object that makes the .hdf file is not DM either. So just one ref to DM where it is either a data transfer or data analysis is perfect.

**Comment by prjemian** [comment]
Also renaming `dm_workflow` to just `workflow`

**Comment by prjemian** [comment]
This is the bluesky data acquisition and workflow kickoff code now: https://github.com/aps-8id-trr/ipython-8idiuser/blob/30410b39d2e5d1c49f5ef29e4700d82784b213a2/user/ad_acquire.py#L160-L182

The workflow only uses information from the PV registers and detector info (from MatLab).
