### ISSUE TITLE
too many metadata files

### ISSUE THREAD

**Issue by sureshnaps** [aps-8id-trr/ipython-8idiuser#80]
@prjemian i am running user ops from spec with metadata, working great. One problem is, multiple hdf's are generated very often, like 20% of the time. In some cases, I saw 3-4 of them per file and in one case, I saw 15 of the. These launch that many analysis as well. 

I tried to comment out the extra file generation, so I thought but it still happens. Since this is for real time only, it would be better if the file exists, then it just quits and it never produces more than one file nor launches more than one file.

**Comment by qzhang234** [comment]
I saw the same problem with Rigaku detector except for me the chances of it occurring is roughly 50%. Would you happen to have some time to take a look at it on Monday before the next run starts?

**Comment by prjemian** [comment]
Sure thing.  I'd like to look at it this morning.  Then, we can meet together in the afternoon to resume the usual group sessions.  What time?  2 pm?

**Comment by prjemian** [comment]
In ed47b3f, a `work_in_progress` boolean is added to block repeated calls for data processing.

**Comment by prjemian** [comment]
Also, add a rising edge detector to process only once per trigger.

**Comment by qzhang234** [comment]
Pete:

Sure, 2 pm sounds good. See you then!


QZ

________________________________
