### ISSUE TITLE
DM_support workflow stops processing with no error shown

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#86]
After some period of time (half hour approx) this past week in which the data management workflow is running (from spec), the workflow stops queueing jobs but does not provide any printed output as to why.  Peculiar is that it initially ran for days without trouble.

**Comment by prjemian** [comment]
Another aspect is that one time, when the helper seemed to stall, the user quit the helper with ^C, then tried to restart.  The helper reported some problem since the trigger value was 1 as it started.  User could not set the PV value back to zero since SPEC was holding that value at 1.  Only by quitting SPEC was user able to reset the trigger PV to zero, the start the helper.

**Comment by prjemian** [comment]
The helper logs information in this diretcory:
`/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/spec_support/.logs`

It would be nice to combine these with the normal session logs.  Had trouble getting the different threads to log into the main logger.  This is a workaround.

**Comment by prjemian** [comment]
The `.workflow_helper.log` file shows these lines about the time this happened:

```
|2019-10-11 22:08:41.090|INFO|spec_DM_support|spec_DM_support|288|MainThread| - before starting data management workflow
|2019-10-11 22:08:41.114|INFO|spec_DM_support|spec_DM_support|293|MainThread| - after starting data management workflow (0.023s)
|2019-10-11 22:08:41.114|INFO|spec_DM_support|spec_DM_support|294|MainThread| - workflow file: /home/8-id-i/2019-3/qzhang201910/O026_Silica_D100_att5_Rq0_00005/O026_Silica_D100_att5_Rq0_00005_0001-100000.hdf
|2019-10-11 22:08:44.886|INFO|spec_DM_support|spec_DM_support|288|MainThread| - before starting data management workflow
|2019-10-11 22:08:44.909|INFO|spec_DM_support|spec_DM_support|293|MainThread| - after starting data management workflow (0.023s)
|2019-10-11 22:08:44.909|INFO|spec_DM_support|spec_DM_support|294|MainThread| - workflow file: /home/8-id-i/2019-3/qzhang201910/O026_Silica_D100_att5_Rq0_00006/O026_Silica_D100_att5_Rq0_00006_0001-100000.hdf
|2019-10-11 22:22:45.913|INFO|spec_DM_support|spec_DM_support|262|MainThread| - workflow helper starting
|2019-10-11 22:23:02.011|INFO|spec_DM_support|spec_DM_support|262|MainThread| - workflow helper starting
|2019-10-11 22:25:39.397|INFO|spec_DM_support|spec_DM_support|262|MainThread| - workflow helper starting
|2019-10-11 22:28:45.714|INFO|spec_DM_support|spec_DM_support|262|MainThread| - workflow helper starting
|2019-10-11 22:29:29.424|INFO|spec_DM_support|spec_DM_support|288|MainThread| - before starting data management workflow
|2019-10-11 22:29:29.448|INFO|spec_DM_support|spec_DM_support|293|MainThread| - after starting data management workflow (0.024s)
|2019-10-11 22:29:29.448|INFO|spec_DM_support|spec_DM_support|294|MainThread| - workflow file: /home/8-id-i/2019-3/qzhang201910/O029_Silica_D100_att5_Rq0_00001/O029_Silica_D100_att5_Rq0_00001_0001-100000.hdf
|2019-10-11 22:29:33.274|INFO|spec_DM_support|spec_DM_support|288|MainThread| - before starting data management workflow
|2019-10-11 22:29:33.297|INFO|spec_DM_support|spec_DM_support|293|MainThread| - after starting data management workflow (0.023s)
|2019-10-11 22:29:33.298|INFO|spec_DM_support|spec_DM_support|294|MainThread| - workflow file: /home/8-id-i/2019-3/qzhang201910/O029_Silica_D100_att5_Rq0_00002/O029_Silica_D100_att5_Rq0_00002_0001-100000.hdf
|2019-10-11 22:29:36.979|INFO|spec_DM_support|spec_DM_support|288|MainThread| - before starting data management workflow
|2019-10-11 22:29:37.003|INFO|spec_DM_support|spec_DM_support|293|MainThread| - after starting data management workflow (0.023s)
|2019-10-11 22:29:37.004|INFO|spec_DM_support|spec_DM_support|294|MainThread| - workflow file: /home/8-id-i/2019-3/qzhang201910/O029_Silica_D100_att5_Rq0_00003/O029_Silica_D100_att5_Rq0_00003_0001-100000.hdf
```

note processes O027 and O028 are missing from the logs

**Comment by prjemian** [comment]
Python *logging* package documentation: https://docs.python.org/3/library/logging.html

**Comment by prjemian** [comment]
It may be time for use of the [*RotatingFileHandler*](https://stackoverflow.com/a/24505345/1046449) feature.

**Comment by prjemian** [comment]
The *RotatingFileHandler* will switch to a new file when the current size will exceed a specified threshold.  It can also limit the number of files in the rotation.

Based on what we've seen so far, I suggest a log file size of 1 MB and a rotation of no more than 9 files.

To implement this, I plan to change the [support library](https://github.com/prjemian/stdlogpj/issues/7) with optional parameters that will choose this file handler as the options describe.

**Comment by prjemian** [comment]
something like this:  `standard_logging_setup(logger_name, maxBytes=1024*1024, backupCount=9)`

**Comment by prjemian** [comment]
Ttesting the revised logging code (35,000 calls, maxBytes=1024*1024, backupCount=5) shows about 0.6 ms per logged line of 176 characters, including file size check and occasional file rotations.

**Comment by prjemian** [comment]
`conda update -c aps-anl-tag stdlogpj` should be v1.0.2

**Comment by prjemian** [comment]
updated the files for account 8idiuser

@qzhang234 : Can you restart the helper code (and that will start to use the new log file size management options).  @sureshnaps and I agreed today that the workflow helper may have appeared stalled since the log files have grown to enormous proportions.  This is the fix.

**Comment by prjemian** [comment]
There are a couple more instances of logging in the SPEC workflow helper.  Re-opening for those.

**Comment by qzhang234** [comment]
There seems to be an error when I tried to start the helper code:

<img width="924" alt="Screen Shot 2019-10-14 at 10 44 52 PM" src="https://user-images.githubusercontent.com/48140482/66798665-6070e680-eed4-11e9-9ac2-c85eecdf1460.png">

**Comment by prjemian** [comment]
@qzhang234 : You are too quick, did not expect you at work now.  I'm still editing and there is more to be done.  Seems I implemented direct file update since the logging was not working as I expected.  The documentation for logging says it is supposed to work the same in threads as in the main program.  I'll switch to that now.

**Comment by prjemian** [comment]
Here's the fix for the error you reported:

```
BYTE = 1
kB = 1024 * BYTE
MB = 1024*kB
```

**Comment by qzhang234** [comment]
@prjemian It's Ok, I can do it tomorrow. The alignment will take about an hour so take your time.
@sureshnaps To switch to Pete's workflow, do I go to ccd_settings_oldstorage.do (the one in Rigaku_8m_Suresh.do) and change 'Use_SPEC_DM_Workflow' to 0?

**Comment by qzhang234** [comment]
@prjemian Ah. Shall I try again?

**Comment by prjemian** [comment]
@qzhang234 : That's the wrong program, type:  `./daemon.sh start`

I'm ready now for you to try it

**Comment by prjemian** [comment]
@qzhang234 @sureshnaps What time will you start in the morning?

**Comment by qzhang234** [comment]
Yes, now it executed without error and the helper box is updating.

We plan to start around 9 or 9:30

**Comment by prjemian** [comment]
not closing the issue until we are convinced it is resolved

**Comment by prjemian** [comment]
I'll join you as soon as I get there.  Laws of physics (and state of Illinois) predict that is ~9:30. -ish.

**Comment by prjemian** [comment]
Oh goody!

**Comment by prjemian** [comment]
Workflow helper logs here:

    /home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/spec_support/.logs/workflow_helper.log

**Comment by prjemian** [comment]
Looks like this:

```
|2019-10-14 22:54:39.812|INFO|30475|spec_DM_support|spec_DM_support|266|MainThread| - workflow helper starting
|2019-10-14 22:54:39.812|INFO|30475|spec_DM_support|spec_DM_support|266|MainThread| - workflow helper starting
|2019-10-14 23:02:50.686|INFO|32043|spec_DM_support|spec_DM_support|266|MainThread| - workflow helper starting
|2019-10-14 23:02:50.686|INFO|32043|spec_DM_support|spec_DM_support|266|MainThread| - workflow helper starting
|2019-10-14 23:03:37.786|INFO|32191|spec_DM_support|spec_DM_support|266|MainThread| - workflow helper starting
|2019-10-14 23:03:37.786|INFO|32191|spec_DM_support|spec_DM_support|266|MainThread| - workflow helper starting
```

Why identical, double entries?

**Comment by prjemian** [comment]
Ok, I understand, there are two loggers writing to this.  I'll need to make one of them look different from the other to identify which to comment out.  Probably this one: https://github.com/aps-8id-trr/ipython-8idiuser/blob/4c1ff36ad4039a6c0ac2ccfea17a557aecfd9d1f/profile_bluesky/startup/spec_support/APS_DM_8IDI.py#L36-L39

**Comment by prjemian** [comment]
now: https://github.com/aps-8id-trr/ipython-8idiuser/blob/6296599e7c7fc412debd6b33ad451319f076a331/profile_bluesky/startup/spec_support/APS_DM_8IDI.py#L35-L39

helper needs a restart:  `./daemon.sh restart`

**Comment by sureshnaps** [comment]
@qzhang234 Yes, set Use_SPEC_DM_Workflow = 0
Note that there is one initialization in the top of the ccd_settings file and there is one under copy_local_data, change both, definitely the one in copy_local_data

There is a copy_local_data_old which you can leave it as is.

**Comment by qzhang234** [comment]
@prjemian Helper is currently running. Should I kill it (kill pid) and restart?

**Comment by qzhang234** [comment]
I switched Use_SPEC_DM_Workflow = 0 at both locations (the one at front was at 0 all the time and somehow it runs), but all jobs are failing. Not sure if I'm starting the workflow wrong.

The job index is Z056. 

Switching back to the old Spec workflow for now.

**Comment by prjemian** [comment]
Workflow log file is updating now.  Using the helper?  Looks like jobs are
processing.  The HTML process view window is updating with completed jobs.

All ok now?

**Comment by qzhang234** [comment]
@prjemian @sureshnaps The DM Workflow stalled at the same stage while the helper is alive and running. I'm switching to the old Spec workflow for now.

<img width="1123" alt="Screen Shot 2019-10-15 at 12 52 29 PM" src="https://user-images.githubusercontent.com/48140482/66856437-d1eb7c00-ef4a-11e9-8306-fae9c580f7bd.png">

**Comment by prjemian** [comment]
Not hard to call that code but no advantage either.  The point of the helper is to *connect* (the step that takes the longest) with all the EPICS PVs before you need to read them.  Calling the connect code after each acquisition is what slows down the process.

I just updated the code around `<trigger_PV>.put(0)` to ensure it does not try to wait AND timeout of no more than 1s.  Can you try again?

**Comment by prjemian** [comment]
Here are the last two acquisitions as logged by the helper:

```
|2019-10-15 12:37:35.274|DEBUG|14167|spec_DM_support|spec_DM_support|284|MainThread| - workflow handling triggered
|2019-10-15 12:37:35.274|INFO|14167|spec_DM_support|spec_DM_support|293|MainThread| - calling start_workflow(analysis=1.0)
|2019-10-15 12:37:35.397|INFO|14167|spec_DM_support|spec_DM_support|298|MainThread| - after starting data management workflow (0.123s)
|2019-10-15 12:37:35.397|INFO|14167|spec_DM_support|spec_DM_support|299|MainThread| - workflow file: /net/s8iddata-old/export/old_8-id-i/2019-3/rinaldi201910/E072_HA_0.04_0_15_180nm_att3_Rq0_00018/E072_HA_0.04_0_15_180nm_att3_Rq0_00018_0001-100000.hdf
|2019-10-15 12:37:35.398|DEBUG|14167|spec_DM_support|spec_DM_support|301|MainThread| - reset trigger: 1.0 (should be '0')
|2019-10-15 12:37:40.200|DEBUG|14167|spec_DM_support|spec_DM_support|284|MainThread| - workflow handling triggered
|2019-10-15 12:37:40.202|INFO|14167|spec_DM_support|spec_DM_support|293|MainThread| - calling start_workflow(analysis=1.0)
|2019-10-15 12:37:40.322|INFO|14167|spec_DM_support|spec_DM_support|298|MainThread| - after starting data management workflow (0.120s)
|2019-10-15 12:37:40.322|INFO|14167|spec_DM_support|spec_DM_support|299|MainThread| - workflow file: /net/s8iddata-old/export/old_8-id-i/2019-3/rinaldi201910/E072_HA_0.04_0_15_180nm_att3_Rq0_00019/E072_HA_0.04_0_15_180nm_att3_Rq0_00019_0001-100000.hdf
|2019-10-15 12:37:40.323|DEBUG|14167|spec_DM_support|spec_DM_support|301|MainThread| - reset trigger: 1.0 (should be '0')
```

**Comment by sureshnaps** [comment]
I see, I get it. We will try it at the next sample start.

**Comment by qzhang234** [comment]
@prjemian @sureshnaps The current users intended to run as it is till the end. Maybe we can test it next Monday when the beam is down?

**Comment by prjemian** [comment]
Ok.  Agreed they have been tortured enough.

**Comment by prjemian** [comment]
Latest version is running now and should be as ready as we can.

```
|2019-10-15 13:46:10.010|INFO|22587|spec_DM_support|spec_DM_support|266|MainThread| - workflow helper starting
```

**Comment by sureshnaps** [comment]
@prjemian The original version that produced multiple files worked very well. Only problem was the multiple files. One thought: just call it once and not worry about multiple times. The original code was meant to do it once as it is meant for real time metadata which will be only once for a dataset. The subsequent calls should just ignore and return without doing anything if the file exists. 

Will this strategy help or the problem is something else?

**Comment by sureshnaps** [comment]
Pete,
Sure, thanks. At 2-30, we have a beamline Ops meeting for which we would disappear for 30 min or so. Do you want to do after 3?
Suresh

**Comment by prjemian** [comment]
Ok

**Comment by prjemian** [comment]
@sureshnaps : Following up on your [comment](https://github.com/aps-8id-trr/ipython-8idiuser/issues/86#issuecomment-544283098), the code before only called the data management process multiple times because it ran through the same loop multiple times for a single trigger.  Now, it only executes that loop once per trigger, based on detecting the trigger's leading edge.

**Comment by prjemian** [comment]
Problem discovered in `spec_DM_support.py` was a syntax error that caused python process to execute with a traceback.  since this was executing from shell script, the error was not reported directly to the console.  And, the console, running in a screen session was immediately closed when the python process ended.

in short: the error message did not print

error was found by running `helper.py` in a console window, after activating the bluesky conda environment.

Suggest continue to run `helper.py` in a console window until the software is proven stable.
