### ISSUE TITLE
DM_support workflow stops processing again

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#87]
As in #86, the DM_support workflow stopped processing again.

**Comment by prjemian** [comment]
Noting that the workflow trigger PV was at value 1 (the helper returns this to zero once it has started a workflow) and the log indicated that the helper had last tried to set this to 0, called `caput 8idi:Reg170 0` from the command line.  Both SPEC and helper resumed processing.

Note, the helper was not stuck.  It was waiting for the PV to reach a value of 0.

**Comment by sureshnaps** [comment]
@prjemian hdf metadata helper code working great. There is one exception that it does not catch. The python code fails when there are special characters in the file name including space. This is not intended but done occasionally done by mistake by the users. When this happens, helper daemon quits. Is there a way to catch the exception and preventing the exiting.
