### ISSUE TITLE
persistent timeout on ca.get("8idi:Reg169")

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#92]
@qzhang234 emailed:

>  Pete, Suresh (@sureshnaps):
> 
> Suresh fixed the file saving location and now we have both the .bin and .hdf (metadata) in one place (an example is /home/8-id-i/2019-3/jemian_201908/P091). 
> 
> However even with both files in place, the cluster analysis still times out at 02-ImmWait. Also, although Bluesky finished running till the end, it's definitely taking longer than supposed to and there's a warning at the end saying that it timed out on ca.get("8idi:Reg169"), which I believe is 'bluesky_scan_number'.
> 
> Any suggestions on what might be causing the problem?

**Comment by prjemian** [comment]
This is the definition: https://github.com/aps-8id-trr/ipython-8idiuser/blob/824cfd96c25e4b68f46d73a5befdb43227aacef1/profile_bluesky/startup/35-DM-support.py#L57

It's a timeout but it is not obvious why.

**Comment by prjemian** [comment]
This, I believe, is the only location where `scan_id` is written: https://github.com/aps-8id-trr/ipython-8idiuser/blob/7b4ebc36dac0d3384eb23bf61e171235d7bbfd8a/user/ad_acquire.py#L184-L186

**Comment by prjemian** [comment]
We changed that from `bps.mv` to `bps.abs_set` because `mv` waits until it confirms the value was set, whereas `abs_set` does not.  Internally, `RE.md["scan_id"]` is a *string* that contains the number of the current scan.  Since `scan_id`, an *EpicsSignal* is configured for the PV `8idi:Reg169`, an EPICS *ao* record (floating point number) PV., the string is converted to integer using `int()`.

Why does this step have persistent trouble?

**Comment by prjemian** [comment]
In context, this is the last step in writing the metadata *after* a scan: https://github.com/aps-8id-trr/ipython-8idiuser/blob/7b4ebc36dac0d3384eb23bf61e171235d7bbfd8a/user/ad_acquire.py#L172-L186

We need this metadata for the success of the workflow.  We cannot obtain a reliable value of the scan_id earlier, such as before the scan starts. 

Can we re-arrange the order in this one method (`update_metadata_postscan()`) and see what happens?

**Comment by prjemian** [comment]
This *may* be the same problem in #88.

**Comment by sureshnaps** [comment]
@prjemian you know the best. If you want to try, we can.

**Comment by prjemian** [comment]
This is the line where the signal is declared: https://github.com/aps-8id-trr/ipython-8idiuser/blob/7b4ebc36dac0d3384eb23bf61e171235d7bbfd8a/profile_bluesky/startup/35-DM-support.py#L57

**Comment by prjemian** [comment]
We could remove `string=True` since the PV is a number and `RE.md["scan_id"]` is also a number.

**Comment by prjemian** [comment]
@danielballan, @tcaswell : We're having trouble with this one EpicsSignal.  Can you offer any insight?

#88 (probably related) has the error dump (expand the triangle for the details).

**Comment by prjemian** [comment]
Definitely related to #88.  Closing here as duplicate.  We see the problem now.
