### ISSUE TITLE
New plot windows appear under console window

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#99]
Takes a user some time to realize the plot window *might* be under their console window.  Why not on top?

**Comment by prjemian** [comment]
notes:

* RHEL7 OS, logged into the workstation (not a remote connection).  
* Interactive ipython session using Qt backend.

```
RunEngine metadata dictionary:
=========== ==============================
key         value
=========== ==============================
beamline_id APS TRR 8-ID-I
login_id    8idiuser@snow.xray.aps.anl.gov
pid         27917
proposal_id None
scan_id     210
versions    =========== ========
            key         value
            =========== ========
            apstools    1.1.14
            bluesky     1.5.4
            databroker  0.13.0
            epics       3.4.0
            matplotlib  3.1.0
            numpy       1.16.4
            ophyd       1.4.0rc1
            pyRestTable 2020.0.2
            spec2nexus  2021.1.3
            =========== ========
=========== ==============================
```

**Comment by prjemian** [comment]
This FAQ seems to be a user preference that goes both ways.  Matplotlib users did not want the window focus stolen from them every time a plot is updated.  Is there a distinction between window first drawn and window updated?  And window focus is another matter entirely.

Stealing focus was seen as the greater sin when bluesky's defaults were picked.  Thus windows are drawn but not made on top.

BUT, it is recommended to move that console window out of the center of the screen or wherever the plot windows seem to appear.

**Comment by prjemian** [comment]
In other locale, @tacaswell replied:

> Because Matplotilb behavior is to not raise the figures to the front
See https://github.com/matplotlib/matplotlib/pull/15440 for an attempt at making it configurable

Once this is included in a public release of matplotlib, then `rcParams['figure.raise_window']` would be changed to get the desired effect.  

*Q*: Where is this term?
*A*: read here: https://matplotlib.org/3.1.1/api/rcsetup_api.html#module-matplotlib.rcsetup

**Comment by carlosgmartin** [comment]
The best option is to let users pick whether/when to raise a window rather than doing so automatically and unexpectedly when calling functions like `pause` and `show`.

**Comment by prjemian** [comment]
The handling of plot windows is scheduled for a major rebuild as described here: https://github.com/bluesky/bluesky-mpl/issues/15

The proposed solution will be a common window for all plots, with each plot in a tab.  See the proposal for details and discussion.

Closing this issue now since we understand the situation at this time.
